# Generated by Django 4.2.7 on 2024-10-23 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_report_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 14, 3, 7, 568941, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
